paradise/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^', include('web.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'web'


urlpatterns = [
    url(r'^$', views.index_view, name='home'),
    url(r'^profile/', views.about_view, name='profile'),
    url(r'^services/', views.services_view, name='services'),
    url(r'^rental/', views.rental_view, name='rental'),
    url(r'^gallery/', views.gallery_view, name='gallery'),
    url(r'^contact/', views.contact_view, name='contacts'),
    url(r'^blog/', views.blog_view, name='blog'),
    url(r'^topography/', views.topography_view, name='topography'),
    url(r'^projects/', views.projects_view, name='projects'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/models.py
from django.db import models


class Site(models.Model):
    details = models.CharField(default="Starts", max_length=20)

web/views.py
from django.shortcuts import render

from .models import Site


def index_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/index.html", context)


def about_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/about.html", context)


def services_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/services.html", context)


def rental_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/car_rental.html", context)


def contact_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/contact.html", context)


def gallery_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/gallery.html", context)


def blog_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/blog.html", context)


def topography_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/typography.html", context)


def projects_view(request):
    details = Site.objects.all()

    context = {
        "details": details,
    }

    return render(request, "Web/projects.html", context)

web/templates/Web/about.html
{% extends 'Web/base_layout_2.html' %}
{% load staticfiles %}
{% block content %}
    <!-- about -->
    <div>
        <p>PARADISE AFRICA EXPEDITIONS LTD was established to provide quality service to both Domestic and
            international tourists.</p>
        <p>Paradise Africa Expeditions ltd is one of the few organizations that can offer a full spectrum of incoming
            tourism services with flexible and efficient solutions, as a one stop supplier. The services we provide
            are of a high standard, and they save time, costs and resources.</p>
        <div class="row">
            <div class="col-sm-4">
                <h3>Mission</h3>
                <p>Our mission is the provision of quality services to our clients while conserving the rich flora
                    and fauna so abundantly found in our region.</p>
            </div>
            <div class="col-sm-4">
                <h3>Vision</h3>
                <p>To be the Africa’s premier travel and tours solution provider.</p>
            </div>
            <div class="col-sm-4">
                <h3>Core Values</h3>
                <ol>
                    <li>Quality Services</li>
                    <li>Customer Centricity</li>
                    <li>Integrity</li>
                    <li>Craft</li>
                </ol>
            </div>
        </div>
    </div>
    <!-- services -->
    <div></div>
{% endblock %}

web/templates/Web/base_layout.html
{% load staticfiles %}
{% load cloudinary %}
<!DOCTYPE>
<html lang="en">
<head>
	<title>Paradise Africa Expeditions</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="" />

	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link rel="stylesheet" href="{% static 'Web/css/bootstrap.css' %}"> <!-- Bootstrap-Core-CSS -->
	<link href="{% static 'Web/css/style.css' %}" rel='stylesheet' type='text/css' />
	<!-- FlexSlider css -->
    <link rel="stylesheet" href="{% static 'Web/css/flexslider.css' %}" type="text/css" media="screen" />
	<!-- //FlexSlider css -->

	<link href="{% static 'Web/css/fontawesome-all.css' %}" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
</head>

<body>
{% block content %}{% endblock %}

{% include 'Web/includes/footer.html' %}
        <!-- bootstrap-modal-pop-up -->
<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				Consult Pro
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="modal-body">
				<img src="{% static 'Web/images/m1.jpg' %}" alt=" " class="img-responsive img-fluid" />
				<p>Ut enim ad minima veniam, quis nostrum
					exercitationem ullam corporis suscipit laboriosam,
					nisi ut aliquid ex ea commodi consequatur? Quis autem
					vel eum iure reprehenderit qui in ea voluptate velit
					esse quam nihil molestiae consequatur, vel illum qui
					dolorem eum fugiat quo voluptas nulla pariatur.
					<i>" Quis autem vel eum iure reprehenderit qui in ea voluptate velit
						esse quam nihil molestiae consequatur.</i></p>
			</div>
		</div>
	</div>
</div>
<!-- //bootstrap-modal-pop-up -->

<!-- js -->
	<script type="text/javascript" src="{% static 'Web/js/jquery-2.2.3.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'Web/js/bootstrap.js' %}"></script> <!-- Necessary-JavaScript-File-For-Bootstrap -->
	<!-- //js -->
<!-- Flex slider-script -->
	<script defer src="{% static 'Web/js/jquery.flexslider.js' %}"></script>
		<script type="text/javascript">

		$(window).load(function(){
          $('.flexslider').flexslider({
            animation: "slide",
            start: function(slider){
              $('body').removeClass('loading');
            }
          });
		});
	  </script>
	<!-- //Flex slider-script -->
    <!-- Calendar -->
    <link rel="stylesheet" href="{% static 'Web/css/jquery-ui.css' %}" />
    <script src="{% static 'Web/js/jquery-ui.js' %}"></script>
    <script>
        $(function() {
            $( "#datepicker" ).datepicker();
        });
    </script>
    <!-- //Calendar -->

<!-- start-smooth-scrolling -->
	<script src="{% static 'Web/js/move-top.js' %}"></script>
	<script src="{% static 'Web/js/easing.js' %}"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();

				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
	</script>
	<!-- //end-smooth-scrolling -->

	<!-- smooth-scrolling-of-move-up -->
	<script>
		$(document).ready(function () {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear'
			};
			*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<!-- //smooth-scrolling-of-move-up -->


	<!-- smooth scrolling js -->
	<script src="{% static 'Web/js/SmoothScroll.min.js' %}"></script>
	<!-- //smooth scrolling js -->
 </body>
</html>

web/templates/Web/contact.html
{% load staticfiles%}
{% load cloudinary %}
<!--A Design by W3layouts
   Author: W3layout
   Author URL: http://w3layouts.com
   License: Creative Commons Attribution 3.0 Unported
   License URL: http://creativecommons.org/licenses/by/3.0/
   -->
<!DOCTYPE html>
<html lang="zxx">
   <head>
     <title>Consult Pro a Corporate Category Bootstrap responsive WebTemplate | Contact :: w3layouts</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="utf-8">
	<meta name="keywords" content="Consult Pro a Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />

	<script type="application/x-javascript">
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<link href="{% static 'Web/css/bootstrap.css'%}" rel='stylesheet' type='text/css' />
	<link href="{% static 'Web/css/style.css'%}" rel='stylesheet' type='text/css' />
	<link href="{% static 'Web/css/fontawesome-all.css'%}" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
   </head>
   <body>
      <!--navbar-->
  <!--Header-->

	<header>
	 <div class="agile-banner_nav">
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
   <a class="navbar-brand" href="{% url 'web:home' %}">Consult Pro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'web:services' %}">Services</a>
      </li>
	  <li class="dropdown nav-item">
								<a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">Pages
									<b class="caret"></b>
								</a>
								<ul class="dropdown-menu agile_short_dropdown">
									<li>
										<a href="{% url 'web:services' %}">Clients</a>
									</li>
									<li>
										<a href="{% url 'web:topography' %}">Typography</a>
									</li>
								</ul>
							</li>

	   <li class="nav-item">
        <a class="nav-link" href="{% url 'web:projects' %}">Projects</a>
      </li>
	   <li class="nav-item active">
        <a class="nav-link" href="{% url 'web:contacts' %}">Contact</a>
      </li>
    </ul>
  </div>
</nav>
 
</div>
</header>
      <!--//navbar-->
      <!-- banner -->
      <div class="inner_page_about">
      </div>
      <!--//banner -->
      <!-- contact -->
<section class="contact py-5" id="contact">
	<div class="container py-3 py-md-3">
			<div class="w3-head-all text-center mb-3">
			<h3>Contact Us</h3>
		   </div>
		<div class="contact-grids row">
			<div class=" col-lg-5 contact-form">
			<h4 class="heading">Get In Touch</h4>
				<form action="#" method="post">
						<input type="text" placeholder="Full Name" required=""/>
						<input type="email" placeholder="Your Mail" required=""/>
						<input type="text" placeholder="Mobile Number" required=""/>
						<textarea placeholder="Message" required=""></textarea>
						<div class="submit1">
							<input type="submit" value="sent">
						</div>
				</form>
			</div>
			<div class=" col-lg-7 map">
				<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d167998.10803373056!2d2.2074740643680624!3d48.85877410312378!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66e1f06e2b70f%3A0x40b82c3688c9460!2sParis%2C+France!5e0!3m2!1sen!2sin!4v1488168816174"></iframe>
			<div class="row">
				<div class="col-lg-4 col-md-4 contact-grid1">
					<i class="fa fa-map-marker" aria-hidden="true"></i>
					<div class="contact-right">
						<p>Address</p>
						<span>3241 USA, Collection building, <span>New York City.</span></span>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 contact-grid1">
					<i class="fa fa-phone" aria-hidden="true"></i>
					<div class="contact-right">
						<p>Phone</p>
						<span>+1(01) 24-212-5665</span>
						<span>+1(01) 24-212-5666</span>
					</div>
				</div>
				<div class="col-lg-4 col-md-4 contact-grid1">
					<i class="fa fa-envelope" aria-hidden="true"></i>
					<div class="contact-right">
						<p>Email</p>
						<a href="mailto:info@example.com">info@example.com</a>
						<a href="mailto:info@example1.com">info@example1.com</a>
					</div>
				</div>
				<div class="clearfix"></div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //contact -->
<!--/footer-->
		<section class="footer py-3">
	<div class="container">
		<div class="row py-4 foot-resp">
	<div class="col-lg-8 bottom-nav-main">
				<ul>
					<li>
						<a href="{% url 'web:home' %}">Home</a>
					</li>
					<li>
						<a href="{% url 'web:services' %}">Services</a>
					</li>
					<li>
						<a href="{% url 'web:projects' %}">Projects</a>
					</li>
					<li>
						<a href="{% url 'web:services' %}">Clients</a>
					</li>
					<li>
						<a href="{% url 'web:contacts' %}">Contact</a>
					</li>
				</ul>
			</div>
			<div class="col-lg-4  footer_social-icons">
				<a class="facebook" href="#">
					<span class="fab fa-facebook-f"></span>
				</a>
				<a class="twitter" href="#">
					<span class="fab fa-twitter"></span>
				</a>
				<a class="pinterest" href="#"> 
					<span class="fab fa-pinterest-p"></span>
				</a>
				<a class="linkedin" href="#">
					<span class="fab fa-linkedin-in"></span>
				</a>
			</div>
			</div>

	 <div class="row py-3">
		<div class="col-lg-4  footer_grid foot-resp ">
			<h3>About Us</h3>
			<p>Sagittis quis turpis vel, facilisis posuere erat. Nulla facilisi. Proin vel commodo leo. Ut mauris tortor, cursus ut massa vitae, iaculis vehicula turpis. Nam libero tempore cum vulputate id posuere erat.</p>
		</div>
		<div class="col-lg-4  footer_grid foot-resp">
			<h3>Latest News</h3>
			<ul class="footer_grid_list">
				<li><i class="fas fa-angle-right" aria-hidden="true"></i>
					<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque vulputate </a>
				</li>
				<li><i class="fas fa-angle-right" aria-hidden="true"></i>
					<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
				</li>
				<li><i class="fas fa-angle-right" aria-hidden="true"></i>
					<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
				</li>
				<li><i class="fas fa-angle-right" aria-hidden="true"></i>
					<a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
				</li>
				<li><i class="fas fa-angle-right" aria-hidden="true"></i>
					<a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
				</li>
			</ul>
		</div>
		<div class="col-lg-4  footer_grid foot-resp">
			<h3>Contact Info</h3>
			<ul class="address">
				<li><i class="fas fa-map-marker-alt" aria-hidden="true"></i>3241 USA, Collection building, <span>New York City.</span></li>
				<li><i class="far fa-envelope-open" aria-hidden="true"></i><a href="mailto:info@example.com">info@example.com</a></li>
				<li><i class="fas fa-phone" aria-hidden="true"></i>+0123 2279 3241</li>
				<li><i class="fas fa-globe" aria-hidden="true"></i><a href="#">info@website.com</a></li>
			</ul>
		</div>
	   </div>
			</div>
		</section>
			<!--//footer-->
			<section class="copy-rights">
			<p class="copyright">© 2018 Consult Pro. All Rights Reserved | Design by <a href="https://w3layouts.com/" target="_blank">w3layouts</a></p>
			</section>
			<!-- bootstrap-modal-pop-up -->
<div class="modal video-modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModal">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				Consult Pro
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>						
			</div>
			<div class="modal-body">
				<img src="{% static 'Web/images/m1.jpg'%}" alt=" " class="img-responsive img-fluid" />
				<p>Ut enim ad minima veniam, quis nostrum 
					exercitationem ullam corporis suscipit laboriosam, 
					nisi ut aliquid ex ea commodi consequatur? Quis autem 
					vel eum iure reprehenderit qui in ea voluptate velit 
					esse quam nihil molestiae consequatur, vel illum qui 
					dolorem eum fugiat quo voluptas nulla pariatur.
					<i>" Quis autem vel eum iure reprehenderit qui in ea voluptate velit 
						esse quam nihil molestiae consequatur.</i></p>
			</div>
		</div>
	</div>
</div>
<!-- //bootstrap-modal-pop-up --> 

    <!-- js -->
	<script type="text/javascript" src="{%static 'Web/js/jquery-2.2.3.min.js'%}"></script>
	<script type="text/javascript" src="{%static 'Web/js/bootstrap.js' %}"></script>
	<!-- //js -->
	<!-- start-smooth-scrolling -->
	<script src="{%static 'Web/js/move-top.js' %}"></script>
	<script src="{%static 'Web/js/easing.js' %}"></script>
	<script>
		jQuery(document).ready(function ($) {
			$(".scroll").click(function (event) {
				event.preventDefault();

				$('html,body').animate({
					scrollTop: $(this.hash).offset().top
				}, 1000);
			});
		});
	</script>
	<!-- //end-smooth-scrolling -->
	
	<!-- smooth-scrolling-of-move-up -->
	<script>
		$(document).ready(function () {
			/*
			var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
			};
			*/

			$().UItoTop({
				easingType: 'easeOutQuart'
			});

		});
	</script>
	<!-- //smooth-scrolling-of-move-up -->
	
	<!-- smooth scrolling js -->
	<script src="{%static 'Web/js/SmoothScroll.min.js' %}"></script>
	<!-- //smooth scrolling js -->
   </body>
</html>

web/templates/Web/includes/footer.html
    <!--/footer-->
    <section class="footer py-3">
        <div class="container">
            <div class="row py-4 foot-resp">
                <div class="col-lg-8 bottom-nav-main">
                    <ul>
                        <li>
                            <a href="i{% url 'web:home' %}">Home</a>
                        </li>
                        <li>
                            <a href="{% url 'web:profile' %}">Profile</a>
                        </li>
                        <li>
                            <a href="{% url 'web:services' %}">Services</a>
                        </li>
                        <li>
                            <a href="{% url 'web:gallery' %}">Gallery</a>
                        </li>
                        <li>
                            <a href="{%  url 'web:blog' %}">Blog</a>
                        </li>
                        <li>
                            <a href="{% url 'web:contacts' %}">Contact</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4  footer_social-icons">
                    <a class="facebook" href="#">
                        <span class="fab fa-facebook-f"></span>
                    </a>
                    <a class="twitter" href="#">
                        <span class="fab fa-twitter"></span>
                    </a>
                    <a class="pinterest" href="#">
                        <span class="fab fa-pinterest-p"></span>
                    </a>
                    <a class="linkedin" href="#">
                        <span class="fab fa-linkedin-in"></span>
                    </a>
                </div>
            </div>
            <div class="container-fluid row py-3">
                <div class="col-lg-4  footer_grid foot-resp ">
                    <h3>About Us</h3>
                    <p>PARADISE AFRICA EXPEDITIONS LTD was established to provide quality service to both Domestic and
                        international tourists.</p>
                    <p>Paradise Africa Expeditions ltd is one of the few organizations that can offer a full spectrum
                        of incoming ourism services with flexible and efficient solutions, as a one stop supplier.
                        The services we provide are of a high standard, and they save time, costs and resources.</p>
                </div>
                <div class="col-lg-4  footer_grid foot-resp">
                    <h3>Latest News</h3>
                    <ul class="footer_grid_list">
                        <li><i class="fas fa-angle-right" aria-hidden="true"></i>
                            <a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque vulputate </a>
                        </li>
                        <li><i class="fas fa-angle-right" aria-hidden="true"></i>
                            <a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
                        </li>
                        <li><i class="fas fa-angle-right" aria-hidden="true"></i>
                            <a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
                        </li>
                        <li><i class="fas fa-angle-right" aria-hidden="true"></i>
                            <a href="#" data-toggle="modal" data-target="#myModal">Dolor amet sed quam vitae</a>
                        </li>
                        <li><i class="fas fa-angle-right" aria-hidden="true"></i>
                            <a href="#" data-toggle="modal" data-target="#myModal">Lorem ipsum neque, vulputate </a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-4  footer_grid foot-resp">
                    <h3>Contact Info</h3>
                    <ul class="address">
                        <li><i class="fas fa-map-marker-alt" aria-hidden="true"></i>2nd Floor, Suite 19, Uganda Hse, Kenyatta Avenue <span>Nairobi, Kenya.</span></li>
                        <li><i class="far fa-envelope-open" aria-hidden="true"></i><a href="mailto:info@paradiseafricaexpeditions
                        .com">info@paradiseafricaexpeditions.com</a></li>
                        <li><i class="fas fa-phone" aria-hidden="true"></i>
                            <a href="tel:+254728808324">0728 808 324</a>/
                            <a href="tel:+254722400064">0722 400 064</a>/
                            <a href="tel:+25420343108">020 343 108</a>
                        </li>
                        <li><i class="fas fa-globe" aria-hidden="true"></i><a href="www.paradiseafricaexpeditions
                        .com">www.paradiseafricaexpeditions</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </section>
    <!--//footer-->
    <section class="copy-rights">
        <p class="copyright">© 2018 Paradise Africa Expeditions. All Rights Reserved | Design by <a href="https://weib
        .herokuapp.com/" target="_blank">weib solutions</a></p>
    </section>

web/templates/Web/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="../index.html">Paradise Africa Expeditions</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
        <ul class="navbar-nav navbar-right ml-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'web:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'web:profile' %}">Profile</a>
            </li>
            <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown" role="button" aria-haspopup="true"
                   aria-expanded="false">Services <span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><a href="{% url 'web:rental' %}">Car Rental</a></li>
                    <li><a href="#">Air Ticketing</a></li>
                    <li><a href="#">Safaris</a></li>
                    <li><a href="#">Hotels & Lodges</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'web:gallery' %}">Gallery</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'web:blog' %}">Blog</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'web:contacts' %}">Contact</a>
            </li>
        </ul>
    </div>
</nav>